name: Sander Hageman
permalink: "/:title"
timezone: Europe/Amsterdam
    
defaults:
  -
    scope:
      path: "assets/img" 
    values:
      image: true
  -
    scope:
      path: "assets/img/thumbnails" 
    values:
      thumbnail: true
   
collections:
  projects:
        output: true
        permalink: "/:collection/:title"

host: 0.0.0.0
