name: Sander Hageman
permalink: "/:title"
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    auto_ids: true
    hard_wrap: false
    
defaults:
  -
    scope:
      path: "_slides" 
    values:
      layout: "iframe"

collections:
  slides:
    output: true
